topics:
  - ^/tf$
  - ^/tf_static$
  - ^/phasespace/(rigids|markers|cameras|errors)$
  - ^/phasespace/stamped/(rigids|markers|cameras)$
  - ^/gt/[^/]+/(pose|odom|path|status)$
  - ^/mocap_debug/(led_markers|led_paths|rigid_markers|rigid_paths|status)$
