topics:
  - /tf
  - /tf_static
  - /phasespace/rigids
  - /phasespace/markers
  - /phasespace/cameras
  - /phasespace/stamped/rigids
  - /phasespace/stamped/markers
  - /phasespace/stamped/cameras
  - /phasespace/errors
  - /gt/{robot_id}/pose
  - /gt/{robot_id}/odom
  - /gt/{robot_id}/status
  - /mocap_debug/status
