topics:
  - /tf
  - /tf_static
  - /phasespace/rigids
  - /phasespace/markers
  - /phasespace/cameras
  - /phasespace/stamped/rigids
  - /phasespace/stamped/markers
  - /phasespace/stamped/cameras
  - /phasespace/errors
  - /gt/{robot_id}/pose
  - /gt/{robot_id}/odom
  - /gt/{robot_id}/status
  - /{robot_id}/odom
  - /{robot_id}/scan
  - /{robot_id}/imu
  - /{robot_id}/camera/color/image_raw
  - /{robot_id}/camera/color/camera_info
  - /{robot_id}/camera/depth/image_rect_raw
  - /{robot_id}/camera/depth/camera_info
